stages:
  - deploy

variables:
  DOCKER_DRIVER: overlay2


build_and_push_to_docker_hub:
  stage: build
  image: docker:latest
  services:
    - docker:latest
  before_script:
    - docker info
  script:
    - docker buildx create --use
    - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
    - docker buildx build --platform linux/amd64,linux/arm64 -t $DOCKERHUB_USERNAME/$DOCKERHUB_BACKEND:latest --push .
  only:
    - main
