services:
  db:
    image: postgres:latest
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: inferno681/shift_fastapi:latest
    env_file: .env
    ports:
      - "8001:8000"
    volumes:
      - ./.env:/app/.env
    depends_on:
      - db
volumes:
  pg_data:
